[build-system]
requires = [
    "setuptools>=61",
    "wheel"
]
build-backend = "setuptools.build_meta"

[project]
name = "wechat-auto4x-sdk"
version = "1.0.0"
description = "wechatauto.sdk的python封装库-社区版"
readme = "README.md"
requires-python = ">=3.13"
authors = [
    {name = "Alex"}
]
dependencies = [
    "pydantic>=2.13.4",
    "pytest>=9.1.1",
    "pytest-asyncio>=1.4.0",
    "websockets>=16.0",
]

[tool.uv.workspace]
members = [
    "examples",
    "tests",
]

[tool.setuptools.packages.find]
where = ["src"]